/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as getUpEarlySol from "./GetUpEarly.sol";
export type { getUpEarlySol };
export type { DrinkBoba } from "./DrinkBoba";
